---
- name: Create monitoring directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ prometheus_directory }}"
    - "{{ grafana_data_directory }}"
    - "{{ grafana_provisioning_directory }}"
    - "{{ grafana_provisioning_directory }}/datasources"
    - "{{ grafana_provisioning_directory }}/dashboards"
    - "{{ grafana_dashboards_directory }}"
    - "{{ loki_directory }}"
    - "{{ promtail_directory }}"

- name: Set Grafana directory ownership
  file:
    path: "{{ grafana_data_directory }}"
    owner: "472"
    group: "472"
    recurse: yes

- name: Generate Prometheus config
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_directory }}/prometheus.yml"
    mode: '0644'

- name: Generate Loki config
  template:
    src: loki.yml.j2
    dest: "{{ loki_directory }}/loki.yml"
    mode: '0644'

- name: Generate Promtail config
  template:
    src: promtail.yml.j2
    dest: "{{ promtail_directory }}/promtail.yml"
    mode: '0644'

- name: Generate Grafana datasources config
  template:
    src: datasources.yml.j2
    dest: "{{ grafana_provisioning_directory }}/datasources/datasources.yml"
    mode: '0644'

- name: Generate Grafana dashboards config
  template:
    src: dashboards.yml.j2
    dest: "{{ grafana_provisioning_directory }}/dashboards/dashboards.yml"
    mode: '0644'

- name: Generate System Overview dashboard
  template:
    src: system-overview.json.j2
    dest: "{{ grafana_dashboards_directory }}/system-overview.json"
    mode: '0644'

- name: Generate Docker Overview dashboard
  template:
    src: docker-overview.json.j2
    dest: "{{ grafana_dashboards_directory }}/docker-overview.json"
    mode: '0644'
  tags: ['grafana_dashboards']

- name: Generate Logs Overview dashboard
  template:
    src: logs-overview.json.j2
    dest: "{{ grafana_dashboards_directory }}/logs-overview.json"
    mode: '0644'

- name: Start Node Exporter container
  docker_container:
    name: node_exporter
    image: "{{ node_exporter_image }}"
    state: started
    restart_policy: unless-stopped
    ports:
      - "{{ node_exporter_port }}:9100"
    command:
      - '--path.rootfs=/host'
      - '--collector.textfile.directory=/textfile'
    volumes:
      - '/:/host:ro,rslave'
      - '/opt/node_exporter_textfile:/textfile:ro'

- name: Start Prometheus container
  docker_container:
    name: prometheus
    image: "{{ prometheus_image }}"
    state: started
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - "{{ prometheus_directory }}/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time={{ prometheus_retention_time }}'
      # Enable external URL and route prefix for reverse proxy
      - '--web.external-url=https://prometheus.{{ domain_name }}'
      - '--web.route-prefix=/'

- name: Start Grafana container
  docker_container:
    name: grafana
    image: "{{ grafana_image }}"
    state: started
    restart_policy: unless-stopped
    network_mode: host
    env:
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
      # Forward authentication configuration
      GF_AUTH_PROXY_ENABLED: "true"
      GF_AUTH_PROXY_HEADER_NAME: "Remote-User"
      GF_AUTH_PROXY_HEADER_PROPERTY: "username"
      GF_AUTH_PROXY_AUTO_SIGN_UP: "true"
      GF_AUTH_PROXY_ENABLE_LOGIN_TOKEN: "false"
      # Additional user info headers
      GF_AUTH_PROXY_HEADERS: "Name:Remote-Name Email:Remote-Email Groups:Remote-Groups"
      # Security settings
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_AUTO_ASSIGN_ORG: "true"
      GF_USERS_AUTO_ASSIGN_ORG_ID: "1"
      GF_USERS_AUTO_ASSIGN_ORG_ROLE: "Admin"
    volumes:
      - "{{ grafana_data_directory }}:/var/lib/grafana"
      - "{{ grafana_provisioning_directory }}:/etc/grafana/provisioning"
      - "{{ grafana_dashboards_directory }}:/var/lib/grafana/dashboards"
  tags: ['grafana_restart']

- name: Start Loki container
  docker_container:
    name: loki
    image: "{{ loki_image }}"
    state: started
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - "{{ loki_directory }}/loki.yml:/etc/loki/local-config.yaml"
    command: 
      - -config.file=/etc/loki/local-config.yaml
      # Configure for reverse proxy
      - -server.path-prefix=/

- name: Start Promtail container
  docker_container:
    name: promtail
    image: "{{ promtail_image }}"
    state: started
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - "{{ promtail_directory }}/promtail.yml:/etc/promtail/config.yml"
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yml

- name: Start cAdvisor container
  docker_container:
    name: cadvisor
    image: "gcr.io/cadvisor/cadvisor:latest"
    state: started
    restart_policy: unless-stopped
    network_mode: host
    privileged: yes
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg

- name: Create textfile directory for node_exporter
  file:
    path: /opt/node_exporter_textfile
    state: directory
    mode: '0755'

- name: Create Docker status script
  copy:
    content: |
      #!/bin/bash
      TEXTFILE_DIR="/opt/node_exporter_textfile"
      TEMP_FILE="$TEXTFILE_DIR/docker_containers.prom.$$"
      PROM_FILE="$TEXTFILE_DIR/docker_containers.prom"
      
      echo "# HELP docker_container_state Container state (1=running, 0=stopped)" > "$TEMP_FILE"
      echo "# TYPE docker_container_state gauge" >> "$TEMP_FILE"
      
      docker ps -a --format "{{ '{{' }}.Names{{ '}}' }}\t{{ '{{' }}.State{{ '}}' }}" | while IFS=$'\t' read -r name state; do
        if [ "$state" == "running" ]; then
          echo "docker_container_state{container_name=\"$name\",state=\"running\"} 1" >> "$TEMP_FILE"
        else
          echo "docker_container_state{container_name=\"$name\",state=\"exited\"} 0" >> "$TEMP_FILE"
        fi
      done
      
      mv "$TEMP_FILE" "$PROM_FILE"
    dest: /opt/docker-metrics.sh
    mode: '0755'

- name: Setup Docker metrics cron job
  cron:
    name: "Generate Docker metrics"
    minute: "*"
    job: "/opt/docker-metrics.sh"

- name: Run Docker metrics script initially
  command: /opt/docker-metrics.sh