---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Install essential packages
  apt:
    name: "{{ essential_packages }}"
    state: present

- name: Set timezone
  shell: timedatectl set-timezone "{{ system_timezone }}"
  changed_when: false
  failed_when: false

- name: Create directories for services
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ base_directory }}"
    - "{{ logs_directory }}"