---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install essential packages
  apt:
    name:
      - curl
      - wget
      - git
      - htop
      - unzip
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
    state: present

- name: Set timezone to UTC
  shell: timedatectl set-timezone UTC
  changed_when: false
  failed_when: false

- name: Create directories for services
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt
    - /opt/logs