---
- name: Create keycloak directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ keycloak_data_directory }}"
    - "{{ keycloak_data_directory }}/postgres"

- name: Start PostgreSQL container for Keycloak
  docker_container:
    name: keycloak-postgres
    image: postgres:15
    state: started
    restart_policy: unless-stopped
    env:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: "{{ keycloak_db_password }}"
    volumes:
      - "{{ keycloak_data_directory }}/postgres:/var/lib/postgresql/data"

- name: Wait for PostgreSQL to be ready
  pause:
    seconds: 15

- name: Start Keycloak container
  docker_container:
    name: keycloak
    image: "{{ keycloak_image }}"
    state: started
    restart_policy: unless-stopped
    ports:
      - "{{ keycloak_port }}:8080"
    env:
      KEYCLOAK_ADMIN: "{{ keycloak_admin_user }}"
      KEYCLOAK_ADMIN_PASSWORD: "{{ keycloak_admin_password }}"
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://keycloak-postgres:5432/keycloak"
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: "{{ keycloak_db_password }}"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
    command: start-dev
    links:
      - keycloak-postgres