---
# Authelia role default variables
authelia_image: "authelia/authelia:latest"
authelia_port: 9091
authelia_directory: "/opt/authelia"
authelia_config_directory: "/opt/authelia/config"
authelia_data_directory: "/opt/authelia/data"
authelia_domain: "auth.{{ domain_name }}"
session_domain: "{{ domain_name }}"

# Secret variables loaded from production .env file
authelia_jwt_secret: "{{ lookup('ini', 'AUTHELIA_JWT_SECRET type=properties file=../inventories/production/.env') }}"
authelia_session_secret: "{{ lookup('ini', 'AUTHELIA_SESSION_SECRET type=properties file=../inventories/production/.env') }}"
authelia_storage_encryption_key: "{{ lookup('ini', 'AUTHELIA_STORAGE_ENCRYPTION_KEY type=properties file=../inventories/production/.env') }}"
authelia_admin_user: "{{ lookup('ini', 'AUTHELIA_ADMIN_USER type=properties file=../inventories/production/.env') }}"
authelia_admin_displayname: "{{ lookup('ini', 'AUTHELIA_ADMIN_DISPLAYNAME type=properties file=../inventories/production/.env') }}"
authelia_admin_email: "{{ lookup('ini', 'AUTHELIA_ADMIN_EMAIL type=properties file=../inventories/production/.env') }}"
authelia_admin_password_hash: "{{ lookup('file', '../inventories/production/.env') | regex_search('AUTHELIA_ADMIN_PASSWORD_HASH=(.*)$', '\\1', multiline=True) | first | regex_replace(\"^'|'$\", '') }}"