all:
  hosts:
    vps:
      ansible_host: 206.166.251.139
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

  vars:
    # Domain for HTTPS (set to your actual domain)
    # Leave as IP if no domain yet - Caddy will use self-signed certs
    domain_name: "amenocturne.space"

    # Service ports
    grafana_port: 3000
    prometheus_port: 9090
    loki_port: 3100
