all:
  hosts:
    vps:
      ansible_host: 206.166.251.139
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/bitlaunch
      ansible_python_interpreter: /usr/bin/python3.12

  vars:
    # Domain for HTTPS (set to your actual domain)
    # Leave as IP if no domain yet - Caddy will use self-signed certs
    domain_name: "amenocturne.space"

    # Service ports
    grafana_port: 3000
    prometheus_port: 9090
    loki_port: 3100
    
    # System configuration
    system_timezone: "UTC"
    apt_cache_valid_time: 3600

    # Directory structure
    base_directory: "/opt"
    logs_directory: "/opt/logs"

    # Service directories
    caddy_directory: "/opt/caddy"
    caddy_config_directory: "/opt/caddy/config"
    caddy_data_directory: "/opt/caddy/data"
    prometheus_directory: "/opt/prometheus"
    grafana_data_directory: "/opt/grafana/data"
    loki_directory: "/opt/loki"
    promtail_directory: "/opt/promtail"

    # Docker images and versions
    caddy_image: "caddy:2-alpine"
    node_exporter_image: "prom/node-exporter:latest"
    prometheus_image: "prom/prometheus:latest"
    grafana_image: "grafana/grafana:latest"
    loki_image: "grafana/loki:latest"
    promtail_image: "grafana/promtail:latest"

    # Network configuration
    http_port: 80
    https_port: 443
    node_exporter_port: 9100

    # SSH configuration
    ssh_port: 22
    ssh_permit_root_login: "yes"
    ssh_password_authentication: "no"
    ssh_pubkey_authentication: "yes"

    # Security configuration
    fail2ban_enabled: true
    unattended_upgrades_enabled: true
    automatic_reboot: false

    # Monitoring configuration
    prometheus_retention_time: "15d"
    grafana_admin_password: "admin"

    # Essential packages
    essential_packages:
      - curl
      - wget
      - git
      - htop
      - unzip
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release

    # Docker packages
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

    # Security packages
    security_packages:
      - fail2ban
      - unattended-upgrades