all:
  hosts:
    vps:
      ansible_host: 168.100.11.130
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/bitlaunch
      ansible_python_interpreter: /usr/bin/python3.12

  vars:
    # Domain for HTTPS (set to your actual domain)
    # Leave as IP if no domain yet - Caddy will use self-signed certs
    domain_name: "amenocturne.space"

    # Service ports
    grafana_port: 3000
    prometheus_port: 9090
    loki_port: 3100
    portainer_port: 9000

    # System configuration
    system_timezone: "UTC"
    apt_cache_valid_time: 3600

    # Directory structure
    base_directory: "/opt"
    logs_directory: "/opt/logs"

    # Service directories
    caddy_directory: "/opt/caddy"
    caddy_config_directory: "/opt/caddy/config"
    caddy_data_directory: "/opt/caddy/data"
    prometheus_directory: "/opt/prometheus"
    grafana_data_directory: "/opt/grafana/data"
    grafana_provisioning_directory: "/opt/grafana/provisioning"
    grafana_dashboards_directory: "/opt/grafana/dashboards"
    loki_directory: "/opt/loki"
    promtail_directory: "/opt/promtail"
    portainer_data_directory: "/opt/portainer/data"

    # Docker images and versions
    caddy_image: "caddy:2-alpine"
    node_exporter_image: "prom/node-exporter:latest"
    prometheus_image: "prom/prometheus:latest"
    grafana_image: "grafana/grafana:latest"
    loki_image: "grafana/loki:latest"
    promtail_image: "grafana/promtail:latest"
    portainer_image: "portainer/portainer-ce:latest"

    # Network configuration
    http_port: 80
    https_port: 443
    node_exporter_port: 9100

    # SSH configuration
    ssh_port: 22
    ssh_permit_root_login: "yes"
    ssh_password_authentication: "no"
    ssh_pubkey_authentication: "yes"

    # Security configuration
    fail2ban_enabled: true
    unattended_upgrades_enabled: true
    automatic_reboot: false

    # Monitoring configuration
    prometheus_retention_time: "15d"
    grafana_admin_password: "admin"

    # Authelia configuration (non-sensitive settings only)
    authelia_image: "authelia/authelia:latest"
    authelia_port: 9091
    authelia_directory: "/opt/authelia"
    authelia_config_directory: "/opt/authelia/config"
    authelia_data_directory: "/opt/authelia/data"
    authelia_domain: "auth.{{ domain_name }}"
    session_domain: "{{ domain_name }}"

    # Essential packages
    essential_packages:
      - curl
      - wget
      - git
      - htop
      - unzip
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release

    # Docker packages
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

    # Security packages
    security_packages:
      - fail2ban
      - unattended-upgrades

    # Deployment user configuration
    deployment_user: "deployer"
    deployment_user_ssh_key: "{{ lookup('file', '~/.ssh/vps-deploy.pub') }}"

    # Projects configuration
    projects:
      - name: infinite-echoes
        type: static
        port: 8001
        auth_required: false
        subdomain: "infinite-echoes"  # Use dedicated subdomain
