---
- name: Update all packages
  apt:
    upgrade: dist
    update_cache: yes

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
  when: fail2ban_enabled

- name: Start and enable fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: yes
  when: fail2ban_enabled

- name: Configure SSH security
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  loop:
    - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin {{ ssh_permit_root_login }}' }
    - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication {{ ssh_password_authentication }}' }
    - { regexp: '^#?PubkeyAuthentication', line: 'PubkeyAuthentication {{ ssh_pubkey_authentication }}' }
    - { regexp: '^#?Port', line: 'Port {{ ssh_port }}' }
  notify: restart ssh

- name: Set up automatic security updates
  apt:
    name: unattended-upgrades
    state: present
  when: unattended_upgrades_enabled

- name: Configure automatic security updates
  copy:
    content: |
      Unattended-Upgrade::Allowed-Origins {
          "${distro_id}:${distro_codename}-security";
          "${distro_id}ESMApps:${distro_codename}-apps-security";
          "${distro_id}ESM:${distro_codename}-infra-security";
      };
      Unattended-Upgrade::AutoFixInterruptedDpkg "true";
      Unattended-Upgrade::MinimalSteps "true";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Automatic-Reboot "{{ automatic_reboot | lower }}";
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
  when: unattended_upgrades_enabled